image: maven:latest

variables:
        MAVEN_CLI_OPTIONS: "--batch-mode"
        MAVEN_SETTINGS_FILE: ".m2/settings.xml"

stages:
        - build
        - test

build:
        stage: build
        tags:
            - java
        script:
                - mvn $MAVEN_CLI_OPTIONS compile
test:
        stage: test
        tags:
            - java
        script:
                - mvn $MAVEN_CLI_OPTIONS test
        artifacts:
                paths:
                        - target/surefire-reports
                        - target/site/it-jacoco
